language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # Could not run on pypy due to lxml
#  - "pypy"
# command to install dependencies
before_install:
  - pip install -e .
  - code-gen --help

# command to run tests
script:
  - nosetests
